# fly.toml file generated for migration-app on 2021-10-13T19:32:25-05:00

app = "postgres-migration-tool"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  POSTGRES_PASSWORD = "pass"

[experimental]
  auto_rollback = false

[[mounts]]
  destination = "/data"
  source = "migration_data"

[[services]]
  processes = ["app"]
  protocol = "tcp"
