# fly.toml file generated for migration-app on 2021-10-13T19:32:25-05:00

app = "draftbit-postgres-migration"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  POSTGRES_PASSWORD = "pass"

[experimental]
  auto_rollback = false

[[services]]
  processes = ["app"]
  protocol = "tcp"
